### ISSUE TITLE
IllegalStateException when running quickstart example

### ISSUE THREAD

**Issue by qsys** [redline-smalltalk/redline-smalltalk#185]
Hopefully, this project is sill alive... I'd love to see this work nicely. However, there hasn't been much activity lately on this project, but well, I just give it a shot.
I followed the instructions on http://www.redline.st/discover/getting-started.html to get started ;), slightly modified for windows. When trying to run the HelloWorld example, I do get an IllegalStateException:

    > java -cp ".;test-classes;lib/redline-0.5-SNAPSHOT.jar;lib/antlr-runtime-3.4.jar;lib/asm-4.1.jar" st.redline.Stic
    java.lang.IllegalStateException: Error: Class 'st.redline.kernel.Symbol' should have been resolved by here.
        at st.redline.lang.ProtoObject.resolveObject(ProtoObject.java:99)
        at st.redline.classloader.Bootstrapper.bootstrapSymbol(Bootstrapper.java:59)
        at st.redline.classloader.Bootstrapper.bootstrap(Bootstrapper.java:20)
        at st.redline.classloader.SmalltalkClassLoader.bootstrap(SmalltalkClassLoader.java:46)
        at st.redline.SticConfiguration.classLoader(SticConfiguration.java:25)
        at st.redline.Stic.classLoader(Stic.java:53)
        at st.redline.Stic.loadProgram(Stic.java:43)
        at st.redline.Stic.runProgram(Stic.java:34)
        at st.redline.Stic.run(Stic.java:30)
        at st.redline.Stic.main(Stic.java:11)
    > java -version
    java version "1.8.0_31"
    Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

OS: windows 7 enterprise edition

**Comment by EduardoCopat** [comment]
I received the same error when running the quick start using Windows.

What worked for me was downloading the source and build it with MVN, as described [here](http://www.redline.st/discover/getting-started.html).

The only difference was the command to run Stic, I used the following (note the different file location and : replaced by ;):

>  java -cp "test-classes;redline-0.5-SNAPSHOT.jar;lib/antlr-runtime-3.4.jar;lib/asm-4.1.jar" st.redline.Stic st.redline.example.HelloWorld
